# Generated by Django 5.2 on 2025-05-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_product_category_product_ctegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ctegory',
            new_name='category',
        ),
    ]
